// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pubs.Models;

public partial class authors
{
    public string au_id { get; set; }

    public string au_lname { get; set; }

    public string au_fname { get; set; }

    public string phone { get; set; }

    public string address { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip { get; set; }

    public bool contract { get; set; }

    public virtual ICollection<titleauthor> titleauthor { get; set; } = new List<titleauthor>();
}