// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace pubs.Models
{
    public partial class byroyaltyResult
    {
        public string au_id { get; set; }
    }
}
