// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace pubs.Models
{
    public partial class reptq3Result
    {
        public string pub_id { get; set; }
        public string type { get; set; }
        public int? cnt { get; set; }
    }
}
