// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pubs.Models;

public partial class sales
{
    public string stor_id { get; set; }

    public string ord_num { get; set; }

    public DateTime ord_date { get; set; }

    public short qty { get; set; }

    public string payterms { get; set; }

    public string title_id { get; set; }

    public virtual stores stor { get; set; }

    public virtual titles title { get; set; }
}